// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1_-rG8nT48anV-L0PzyLpSGXHzvkMpzo',
    appId: '1:28026091049:web:2c8f8bddf0b1624ccdce38',
    messagingSenderId: '28026091049',
    projectId: 'torrentx-d1693',
    authDomain: 'torrentx-d1693.firebaseapp.com',
    databaseURL: 'https://torrentx-d1693-default-rtdb.firebaseio.com',
    storageBucket: 'torrentx-d1693.appspot.com',
    measurementId: 'G-MRC91W7G2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUy62kmNTzolwVj9T5aljt49xHHBUhjGY',
    appId: '1:28026091049:android:929735e266a0fa9fcdce38',
    messagingSenderId: '28026091049',
    projectId: 'torrentx-d1693',
    databaseURL: 'https://torrentx-d1693-default-rtdb.firebaseio.com',
    storageBucket: 'torrentx-d1693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDyA66KbT7wUkZZTP1Oa63ZeMipV-TwA',
    appId: '1:28026091049:ios:42dbda22f8a86788cdce38',
    messagingSenderId: '28026091049',
    projectId: 'torrentx-d1693',
    databaseURL: 'https://torrentx-d1693-default-rtdb.firebaseio.com',
    storageBucket: 'torrentx-d1693.appspot.com',
    androidClientId: '28026091049-jrqpdfh1rvtkvp5qgt2ij4h7lcl9cvit.apps.googleusercontent.com',
    iosClientId: '28026091049-3125ksnlacovvr816b530i67h91a08p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.torrentx',
  );
}
